import {
  Briefcase,
  Building2,
  MessagesSquare,
  Users,
  Library,
  CalendarRange,
  KanbanSquare,
  Sparkles,
  Timer,
  ShoppingBag,
  GraduationCap,
} from 'lucide-react';

// Upcoming modules — each gets a real route + landing page until it ships.
export const UPCOMING_FEATURES = [
  {
    slug: 'placements',
    name: 'Placement Hub',
    icon: Briefcase,
    phase: 'Phase 2',
    tagline: 'Track every placement drive in one place',
    bullets: [
      'Companies, roles, packages and eligibility at a glance',
      'Personal status tracker: Applied → Shortlisted → Interview → Offer',
      'Deadlines and round schedules so you never miss a drive',
    ],
  },
  {
    slug: 'internships',
    name: 'Internship Board',
    icon: Building2,
    phase: 'Phase 2',
    tagline: 'Every internship opportunity, curated for the batch',
    bullets: [
      'Company, location, remote/hybrid tags',
      'Direct apply links with eligibility and deadlines',
      'Batch-shared: anyone can post an opening they found',
    ],
  },
  {
    slug: 'community',
    name: 'Community Feed',
    icon: MessagesSquare,
    phase: 'Phase 3',
    tagline: 'The batch timeline — wins, questions and updates',
    bullets: [
      'Posts, photos, polls and questions',
      'Likes, comments, bookmarks, hashtags and mentions',
      'Share achievements and internship updates',
    ],
  },
  {
    slug: 'directory',
    name: 'Student Directory',
    icon: Users,
    phase: 'Phase 3',
    tagline: 'Find the right batchmate for anything',
    bullets: [
      'Searchable profiles: skills, interests, clubs, languages',
      'LinkedIn, GitHub and portfolio links',
      'Discover who can help with what',
    ],
  },
  {
    slug: 'resources',
    name: 'Resource Library',
    icon: Library,
    phase: 'Phase 4',
    tagline: 'Notes grow up: every file format, fully searchable',
    bullets: [
      'PDF, Word, Excel, PPT, ZIP, videos and links',
      'Organized by subject, semester, professor and tags',
      'Global search across everything',
    ],
  },
  {
    slug: 'events',
    name: 'Events',
    icon: CalendarRange,
    phase: 'Phase 4',
    tagline: 'Campus events with RSVP and memories built in',
    bullets: [
      'Event pages with registration and RSVP',
      'Attendance, certificates and event galleries',
      'Synced with your planner',
    ],
  },
  {
    slug: 'projects',
    name: 'Group Projects',
    icon: KanbanSquare,
    phase: 'Phase 4',
    tagline: 'Kanban boards for every group assignment',
    bullets: [
      'Create project groups with your team',
      'Tasks, deadlines, progress and comments',
      'Shared files per project',
    ],
  },
  {
    slug: 'ai-tools',
    name: 'AI Tools',
    icon: Sparkles,
    phase: 'Phase 5',
    tagline: 'An AI studio tuned for MBA workflows',
    bullets: [
      'Document and case-study summarization',
      'Resume review and interview question practice',
      'Flashcards, presentation outlines and a prompt library',
    ],
  },
  {
    slug: 'study-tools',
    name: 'Study Tools',
    icon: Timer,
    phase: 'Phase 5',
    tagline: 'Focus tools that build streaks, not stress',
    bullets: [
      'Pomodoro and study timers',
      'Habit tracker with daily and weekly goals',
      'Progress analytics and study streaks',
    ],
  },
  {
    slug: 'marketplace',
    name: 'Marketplace',
    icon: ShoppingBag,
    phase: 'Phase 5',
    tagline: 'Buy and sell within the batch, zero commission',
    bullets: [
      'Books, laptops, calculators, hostel items',
      'MBA prep material that already got someone placed',
      'Filters by category and price',
    ],
  },
  {
    slug: 'skills',
    name: 'Skill Exchange',
    icon: GraduationCap,
    phase: 'Phase 5',
    tagline: 'Everyone teaches, everyone learns',
    bullets: [
      'Offer what you know — Excel, Power BI, public speaking…',
      'Book peer sessions with batchmates',
      'Ratings and reviews build your mentor profile',
    ],
  },
];
