models:
  - name: DeepSeek V4 Pro
    provider: openai

    apiBase: https://integrate.api.nvidia.com/v1
    apiKey: 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

    model: deepseek-ai/deepseek-v4-pro

    roles:
      - chat
      - edit
      - apply

    defaultCompletionOptions:
      contextLength: 1000000
      maxTokens: 4096
      temperature: 0.2

  - name: Qwen 3.5 122B
    provider: openai

    apiBase: https://integrate.api.nvidia.com/v1
    apiKey: YOUR_NEW_NVIDIA_API_KEY

    model: qwen/qwen3.5-122b-a10b

    roles:
      - chat
      - edit
      - apply

    defaultCompletionOptions:
      contextLength: 262144
      maxTokens: 4096
      temperature: 0.2