module.exports = {
  slug: 'mba',
  name: 'Master of Business Administration',
  version: '1.0.0',
  description: 'Business school platform — notes, placements, finance, community, AI tools',
  features: {
    notes: true,
    finance: true,
    resume: true,
    placements: true,
    internships: true,
    community: true,
    ai: true,
    dailyCase: true,
    dailyBriefing: true,
    studyTools: true,
    events: true,
    marketplace: true,
    skills: true,
    projects: true,
    resources: true,
    journal: true,
    entertainment: true,
    pivot: true,
    starStories: true,
    readiness: true,
    companies: true,
  },
  defaults: {
    dashboardOrder: ['briefing', 'study', 'career', 'community', 'me'],
  },
};
