module.exports = {
  slug: 'general',
  name: 'DATAD',
  version: '1.0.0',
  description: 'AI-powered personal operating system for students — discipline-agnostic. The default for every field of study; MBA-specific tooling lives in the mba module and is opted into via profile/course, not assumed.',
  features: {
    notes: true,
    finance: true,
    resume: true,
    placements: true,
    internships: true,
    community: true,
    ai: true,
    dailyCase: true,
    dailyBriefing: true,
    studyTools: true,
    events: true,
    marketplace: true,
    skills: true,
    projects: true,
    resources: true,
    journal: true,
    entertainment: true,
    pivot: true,
    starStories: true,
    readiness: true,
    companies: true,
  },
  defaults: {
    dashboardOrder: ['briefing', 'study', 'career', 'community', 'me'],
  },
};
